cloud:
  aws:
    credentials:
      accessKey: AKIAX3BNHSUQRODII4PU
      secretKey: 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
    s3:
      bucket: waggle-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false