spring:
  #  profiles:
  #    include:
  #      - security
  #      - real-db
  #      - s3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  use-fqn: true
