name: waggle dev CI/CD

on:
  push:
    branches:
      - performance-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build with Gradle & Upload Image to ECR
        run: ./gradlew -Pdev clean jib

      - name: Remove old Docker images (dev server)
        run: |
          docker rmi -f 654654421569.dkr.ecr.ap-northeast-2.amazonaws.com/waggle/prod:latest || true
          docker system prune -a --force || true

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy/.platform/nginx/conf.d
          cp docker-compose.yml deploy/docker-compose.yml
          cp -r .ebextensions-dev deploy/.ebextensions
          cp .platform/nginx/conf.d/proxy-dev.conf deploy/.platform/nginx/conf.d/proxy.conf
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          application_name: waggle-performance-test
          environment_name: Waggle-performance-test-env
          version_label: waggle-prod-${{steps.current-time.outputs.formattedTime}}
          region: ${{ secrets.DEV_AWS_REGION }}
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 500